jp_job_progress:
    path:     /jp/progress
    defaults: { _controller: JPBundle:JobProgress:progress }

jp_job_progress_all:
    path:     /jp/progress/all
    defaults: { _controller: JPBundle:JobProgress:progressAll }
