jp_job_progress:
    path:     /jpb/progress/user
    defaults: { _controller: JPBundle:JobProgress:getProgressUser }

jp_job_progress_all:
    path:     /jpb/progress/all
    defaults: { _controller: JPBundle:JobProgress:getProgressAll }
