services:
#    jp.example:
#        class: callebstrom\JPBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    job_handle_service:
        class: callebstrom\JPBundle\Controller\JobHandleController
        calls:
            - [setContainer, ["@service_container"]]

    kernel.listener.job_event_listener:
        class: callebstrom\JPBundle\Events\JobEventListener
        tags:
            - { name: kernel.event_listener, event: jpb.events.job_aborted, method: onJobAborted }
            - { name: kernel.event_listener, event: jpb.events.job_suspended, method: onJobSuspended }